import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import { existsSync, readFileSync, writeFileSync, rmSync, copyFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __buildDir = dirname(fileURLToPath(import.meta.url));
const ortNodeAbsPath   = resolve(__buildDir, "node_modules", "onnxruntime-node");
const ortNodeAvailable = existsSync(ortNodeAbsPath);
if (!ortNodeAvailable) console.warn("[build] WARNING: onnxruntime-node not found");

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
// import.meta.url shim — @anthropic-ai/claude-agent-sdk calls createRequire(import.meta.url)
// at module scope; without this it throws on undefined and the plugin fails to load.
var __import_meta_url = typeof __filename !== "undefined"
	? require("node:url").pathToFileURL(__filename).href
	: "file:///main.js";
// Inject onnxruntime-node under the Symbol.for("onnxruntime") key so
// EmbeddingService can pick it up without a second require() call.
${ortNodeAvailable ? `;(function(){
	try {
		var _ort = require(${JSON.stringify(ortNodeAbsPath)});
		globalThis[Symbol.for("onnxruntime")] = _ort;
		console.log("[RAG] onnxruntime-node injected");
	} catch(_e) { console.warn("[RAG] onnxruntime-node injection failed:", _e.message); }
})();` : `/* onnxruntime-node not available at build time */`}
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian", "electron",
		"__ORT_ABS_PATH__",   // placeholder — replaced by patchBundle() with real absolute path
		"@codemirror/autocomplete", "@codemirror/collab", "@codemirror/commands",
		"@codemirror/language", "@codemirror/lint", "@codemirror/search",
		"@codemirror/state", "@codemirror/view",
		"@lezer/common", "@lezer/highlight", "@lezer/lr",
		...builtinModules,
		...builtinModules.map(m => `node:${m}`),
	],
	format: "cjs",
	define: { "import.meta.url": "__import_meta_url" },
	loader: { ".svg": "text" },
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

// Local dev convenience only: when this repo sits inside an Obsidian vault's
// plugins/ folder alongside a sibling "large-language-models" folder (the one
// Obsidian actually loads from), mirror build output there too. Absent in CI
// (a plain checkout has no such sibling folder), so every step below is a
// best-effort no-op there — the repo-root copies (main.js/manifest.json/
// styles.css) are what release.yml's attest/upload steps actually use.
const liveVaultFolder = "../large-language-models";
const liveVaultFolderExists = existsSync(liveVaultFolder);

/**
 * Patch the built bundle:
 * 1. Replace the "__ORT_ABS_PATH__" placeholder with the real absolute path.
 */
function patchBundle() {
	const bundlePath = "main.js";
	let src = readFileSync(bundlePath, "utf8");
	const placeholder = '"__ORT_ABS_PATH__"';
	if (src.includes(placeholder)) {
		src = src.replace(placeholder, JSON.stringify(ortNodeAbsPath));
		console.log("[build] Patched ORT path in bundle:", ortNodeAbsPath);
	} else {
		console.warn("[build] WARNING: ORT placeholder not found in bundle");
	}
	writeFileSync(bundlePath, src, "utf8");
}

function copyPluginAssets() {
	if (!liveVaultFolderExists) return;
	copyFileSync("main.js", `${liveVaultFolder}/main.js`);
	copyFileSync("manifest.json", `${liveVaultFolder}/manifest.json`);
	copyFileSync("styles.css", `${liveVaultFolder}/styles.css`);
}

function cleanupDeadFiles() {
	if (!liveVaultFolderExists) return;
	// embed-worker.js was used by the abandoned child-process approach — remove it.
	try { rmSync(`${liveVaultFolder}/embed-worker.js`); } catch (_) {}
	// ort-wasm-simd-threaded.wasm was copied by the old WASM approach — remove it.
	try { rmSync(`${liveVaultFolder}/wasm`, { recursive: true }); } catch (_) {}
}

if (prod) {
	await context.rebuild();
	patchBundle();
	copyPluginAssets();
	cleanupDeadFiles();
	process.exit(0);
} else {
	await context.rebuild();
	patchBundle();
	copyPluginAssets();
	cleanupDeadFiles();
	await context.watch();
}
