export const claude = "claude"
export const claudeCode = "claudeCode"
export const openAI = "openAI"
export const gemini = "gemini"
export const GPT4All = "GPT4All"
export const ollama = "ollama"
export const lmStudio = "lmStudio"
export const mistral = "mistral"

export const claudeCodeEndpoint = "claudeCodeAgent"

export const claudeSonnet46Model = "claude-sonnet-4-6"
export const claudeOpus46Model = "claude-opus-4-6"
export const claudeHaiku45Model = "claude-haiku-4-5-20251001"
export const claudeValidationModel = claudeSonnet46Model
export const gemini2FlashStableModel = "gemini-2.0-flash"
export const gemini2FlashLiteModel = "gemini-2.0-flash-lite"
export const gemini25ProModel = "gemini-2.5-pro"
export const gemini25FlashModel = "gemini-2.5-flash"
export const gemini25FlashLiteModel = "gemini-2.5-flash-lite"
export const gemini3ProPreviewModel = "gemini-3-pro-preview"
export const geminiFlashLatestModel = "gemini-flash-latest"
export const geminiFlashLiteLatestModel = "gemini-flash-lite-latest"
export const openAIModel = "gpt-3.5-turbo"

export const messages = "messages"
export const assistant = "assistant"
export const chat = "chat"
export const images = "images"
