import { ImageSize, ViewType } from "Types/types";
import LLMPlugin from "main";
import { DropdownComponent, Setting } from "obsidian";
import { models } from "utils/models";
import {
	getSettingType,
} from "utils/utils";
import { chat, claudeCodeEndpoint, GPT4All, messages, openAI } from "utils/constants"

export class SettingsContainer {
	viewType: ViewType;

	constructor(private plugin: LLMPlugin, viewType: ViewType) {
		this.viewType = viewType;
	}

	async generateSettingsContainer(parentContainer: HTMLElement) {
		this.resetSettings(parentContainer);
		this.generateModelSettings(parentContainer);
	}

	resetSettings(parentContainer: Element) {
		parentContainer.empty();
	}

	generateModelSettings(parentContainer: HTMLElement) {
		const settingType = getSettingType(this.viewType);
		const viewSettings = this.plugin.settings[settingType];
		const endpoint = viewSettings.modelEndpoint;
		const modelType = viewSettings.modelType;
		if (endpoint === "images") {
			this.generateImageSettings(parentContainer, viewSettings.model);
		}
		if (endpoint === "moderations") {
			this.generateModerationsSettings(parentContainer);
		}
		if (endpoint === claudeCodeEndpoint) {
			// Claude Code Agent SDK manages its own model config;
			// no temperature/tokens settings needed.
			return;
		}
		if (endpoint === chat || messages) {
			this.generateChatSettings(parentContainer, modelType);
			if (this.plugin.settings.enableFileContext) {
				this.generateContextSettings(parentContainer);
			}
		}
	}

	generateImageSettings(parentContainer: HTMLElement, model: string) {
		const settingType = getSettingType(this.viewType);
		const viewSettings = this.plugin.settings[settingType];
		const imageSizes = ["1024x1024", "1536x1024", "1024x1536", "auto"];

		new Setting(parentContainer)
			.setName("Number of images")
			.setDesc(
				"The number of images generated by the model. Must be between 1 and 10."
			)
			.addText((text) => {
				text.setValue(`${viewSettings.imageSettings.numberOfImages}`);
				text.inputEl.type = "number";
				text.onChange((change) => {
					viewSettings.imageSettings.numberOfImages =
						parseInt(change);
					this.plugin.saveSettings();
				});
			});

		new Setting(parentContainer)
			.setName("Response format")
			.setDesc(
				"The format in which the generated images are returned. Must be one of url or b64_json. URLs are only valid for 60 minutes after the image has been generated."
			)
			.addDropdown((dropdown: DropdownComponent) => {
				dropdown.addOption("", "Select a Format");
				dropdown.addOption("url", "URL");
				dropdown.addOption("b64_json", "Base64 JSON");
				dropdown.onChange((change) => {
					viewSettings.imageSettings.response_format = change as
						| "url"
						| "b64_json";
					this.plugin.saveSettings();
				});
			});

		new Setting(parentContainer)
			.setName("Image size")
			.setDesc(
				"The size of the generated images. Must be one of 1024x1024, 1536x1024, 1024x1536, or auto."
			)
			.addDropdown((dropdown: DropdownComponent) => {
				dropdown.addOption("", "Select a size");
				imageSizes.map((size) => {
					dropdown.addOption(size, size);
				});
				dropdown.onChange((change: ImageSize) => {
					viewSettings.imageSettings.size = change;
					this.plugin.saveSettings();
				});
			});

		new Setting(parentContainer)
			.setName("Quality")
			.setDesc(
				"The quality of the image that will be generated. Higher quality takes longer and costs more."
			)
			.addDropdown((dropdown: DropdownComponent) => {
				dropdown.addOption("", "Select quality");
				dropdown.addOption("low", "Low");
				dropdown.addOption("medium", "Medium");
				dropdown.addOption("high", "High");
				dropdown.onChange((change: "low" | "medium" | "high") => {
					viewSettings.imageSettings.quality = change;
					this.plugin.saveSettings();
				});
			});
	}

	generateChatSettings(parentContainer: HTMLElement, modelType: string) {
		const settingType = getSettingType(this.viewType);
		const viewSettings = this.plugin.settings[settingType];

		new Setting(parentContainer)
			.setName("Temperature")
			.setDesc(
				modelType !== GPT4All
					? "Defaults to 1. What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. We generally recommend altering this or top_p but not both."
					: "Higher temperatures (eg., 1.2) increase randomness, resulting in more imaginative and diverse text. Lower temperatures (eg., 0.5) make the output more focused, predictable, and conservative. A safe range would be around 0.6 - 0.85"
			)
			.addText((text) => {
				text.setValue(`${viewSettings.chatSettings.temperature}`);
				text.inputEl.type = "number";
				text.onChange((change) => {
					viewSettings.chatSettings.temperature = parseFloat(change);
					this.plugin.saveSettings();
				});
			});

		new Setting(parentContainer)
			.setName("Tokens")
			.setDesc("Maximum number of tokens in the response. Set to 0 to use the model's default. Higher values allow longer responses.")
			.addText((text) => {
				text.setValue(`${viewSettings.chatSettings.maxTokens}`);
				text.inputEl.type = "number";
				text.onChange((change) => {
					viewSettings.chatSettings.maxTokens = parseInt(change);
					this.plugin.saveSettings();
				});
			});

		if (modelType === openAI) {
			new Setting(parentContainer)
				.setName("Frequency penalty")
				.setDesc(
					"Defaults to 0. Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim."
				)
				.addText((text) => {
					text.setValue(
						`${viewSettings.chatSettings.openAI?.frequencyPenalty}`
					);
					text.inputEl.type = "number";
					text.onChange((change) => {
						viewSettings.chatSettings.openAI!.frequencyPenalty =
							parseFloat(change);
						this.plugin.saveSettings();
					});
				});

			new Setting(parentContainer)
				.setName("Log probs")
				.setDesc(
					"Defaults to false. Whether to return log probabilities of the output tokens or not. If true, returns the log probabilities of each output token returned in the content of message."
				)
				.addToggle((value) => {
					value.onChange((change) => {
						viewSettings.chatSettings.openAI!.logProbs = change;
						this.plugin.saveSettings();
					});
				});

			new Setting(parentContainer)
				.setName("Top log probs")
				.setDesc(
					"An integer between 0 and 5 specifying the number of most likely tokens to return at each token position, each with an associated log probability. logprobs must be set to true if this parameter is used."
				)
				.addText((text) => {
					text.setValue(
						`${viewSettings.chatSettings.openAI?.topLogProbs}`
					);
					text.inputEl.type = "number";
					text.onChange((change) => {
						viewSettings.chatSettings.openAI!.topLogProbs =
							parseFloat(change);
						this.plugin.saveSettings();
					});
				});

			new Setting(parentContainer)
				.setName("Presence penalty")
				.setDesc(
					"Defaults to 0. Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics."
				)
				.addText((text) => {
					text.setValue(
						`${viewSettings.chatSettings.openAI?.presencePenalty}`
					);
					text.inputEl.type = "number";
					text.onChange((change) => {
						viewSettings.chatSettings.openAI!.presencePenalty =
							parseFloat(change);
						this.plugin.saveSettings();
					});
				});

			new Setting(parentContainer)
				.setName("Response format")
				.setDesc(
					`An object specifying the format that the model must output. Compatible with GPT-4 turbo and all GPT-3.5 turbo models newer than gpt-3.5-turbo-1106. Setting to { "type": "json_object" } enables JSON mode, which guarantees the message the model generates is valid JSON.`
				)
				.addText((text) => {
					text.setValue(
						`${viewSettings.chatSettings.openAI?.responseFormat}`
					);
					text.onChange((change) => {
						viewSettings.chatSettings.openAI!.responseFormat =
							change;
						this.plugin.saveSettings();
					});
				});

			new Setting(parentContainer)
				.setName("Top p")
				.setDesc(
					"Defaults to 1. An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered."
				)
				.addText((text) => {
					text.setValue(`${viewSettings.chatSettings.openAI?.topP}`);
					text.inputEl.type = "number";
					text.onChange((change) => {
						viewSettings.chatSettings.openAI!.topP =
							parseFloat(change);
						this.plugin.saveSettings();
					});
				});
		}
	}

	generateContextSettings(parentContainer: HTMLElement) {
		const settingType = getSettingType(this.viewType);
		const viewSettings = this.plugin.settings[settingType];
		const contextSettings = viewSettings.contextSettings;

		// Context section header
		const contextHeader = parentContainer.createEl("h3", {
			text: "Context Settings",
		});
		contextHeader.style.marginTop = "1.5em";
		contextHeader.style.marginBottom = "0.5em";

		// Include active file
		new Setting(parentContainer)
			.setName("Include active file")
			.setDesc(
				"Automatically include the content of the currently active file in the context sent to the AI."
			)
			.addToggle((toggle) => {
				toggle
					.setValue(contextSettings.includeActiveFile)
					.onChange(async (value) => {
						contextSettings.includeActiveFile = value;
						await this.plugin.saveSettings();
					});
			});

		// Include selection
		new Setting(parentContainer)
			.setName("Include selected text")
			.setDesc(
				"Automatically include any text selected in the editor in the context sent to the AI."
			)
			.addToggle((toggle) => {
				toggle
					.setValue(contextSettings.includeSelection)
					.onChange(async (value) => {
						contextSettings.includeSelection = value;
						await this.plugin.saveSettings();
					});
			});

		// Context token budget percentage
		new Setting(parentContainer)
			.setName("Context token budget (%)")
			.setDesc(
				"Percentage of max tokens to allocate for context (0-100). The remaining percentage is reserved for the AI's response. For example, 70% means 70% for context and 30% for the response."
			)
			.addText((text) => {
				text.setValue(`${contextSettings.maxContextTokensPercent}`);
				text.inputEl.type = "number";
				text.inputEl.min = "0";
				text.inputEl.max = "100";
				text.onChange((change) => {
					const value = parseInt(change);
					if (!isNaN(value) && value >= 0 && value <= 100) {
						contextSettings.maxContextTokensPercent = value;
						this.plugin.saveSettings();
					}
				});
			});

	}

	generateModerationsSettings(parentContainer: HTMLElement) { }
}
